### ISSUE TITLE
text too small

### ISSUE THREAD

**Issue by ghost** [jakeisnt/site#75]
looks better scaled up to 150-200% on a 3456 × 2234 screen (16" mac)

also sup nice website and notes i still havent tried out clojurescript but i hope to someday :) also nix

**Comment by jakeisnt** [comment]
I agree! Thanks. 

Clojure/script is cool but I stopped using it (the standard library adds ~1.5mb to the bundle). This is a static site generator in Clojure (JVM, not JS) and pulls in JS for some small front-end things. 

Long-term plan (next weekend lol?) is to make a lisp syntax for JS of my own that has the same semantics as JS and convert the scripts!! As macros are nice to have but large websites are not.

**Comment by jakeisnt** [comment]
Increased the font size and switched to a more legible font :  ) I think this is solved!

**Comment by ghost** [comment]
Yay!
